name: Rego Lint and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Regal
        uses: StyraInc/setup-regal@v1
        with:
          version: latest

      - name: Lint
        # Disable the line-length check for now, as it's too strict: it flags
        # the long regexes in various classification policies.
        run: regal lint --format=github --disable=line-length ./classification/labels/

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest

      - name: Run OPA Tests
        run: opa test classification/labels/*.rego -v
